import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { locations, locationBySlug } from "@/data/site-content";
import { site } from "@/config/site";
import { JsonLd } from "@/lib/seo";
export const dynamicParams=false;
export function generateStaticParams(){return locations.map(({slug})=>({city:slug}));}
export async function generateMetadata({params}:{params:Promise<{city:string}>}):Promise<Metadata>{const{city}=await params;const item=locationBySlug(city);if(!item)return{};return{title:`Toilet Cubicles & Washroom Partitions in ${item.city}`,description:`Discuss commercial restroom cubicles, washroom partitions, UMP, lockers and coordinated washroom systems for projects in ${item.city}.`,robots:item.indexable?{index:true,follow:true}:{index:false,follow:true},alternates:{canonical:`/locations/${city}/`}};}
export default async function CityPage({params}:{params:Promise<{city:string}>}){const{city}=await params;const item=locationBySlug(city);if(!item)notFound();return <><JsonLd data={{"@context":"https://schema.org","@type":"Service",name:`Commercial washroom solutions in ${item.city}`,provider:{"@id":`${site.url}/#organization`},areaServed:{"@type":"City",name:item.city}}}/><header className="page-hero"><div className="container"><p className="cp-kicker">{item.region} · Project enquiries</p><h1>Commercial washroom solutions in {item.city}.</h1><p className="lede">{item.focus}</p></div></header><section className="cp-section"><div className="container cp-two-col"><div><h2>What we can discuss.</h2><p>Restroom cubicles, washroom partitions, UMP, Junior Cubicles, HPL lockers, shower cubicles, changing-room cubicles, cladding, storage, profiles and hardware.</p></div><div className="cp-feature-stack"><article><h3>Share the project context</h3><p>Include the city, site location, application, approximate quantity and intended programme.</p></article><article><h3>Confirm the system</h3><p>Final material grade, thickness, hardware, mounting and configuration follow the approved project specification.</p></article><Link className="cp-button cp-button-accent" href="/contact/">Request a quote for {item.city} ↗</Link></div></div></section></>;}
